# Site settings
title: Software and Data Carpentry at the University of Michigan
email: pschloss@umich.edu
description: > # this means to ignore newlines until "baseurl:"
   The website for the University of Michigan chapter of the Software and Data Carpentry organizations.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://umswc.github.io" # the base hostname & protocol for your site
twitter_username: #patschloss
github_username:  umswc #schlosslab
array: []

# Build settings
markdown: kramdown

collections:
  instructors:
    output: true
  workshops:
    output: true
  news:
    output: true
